### ISSUE TITLE
Issue in KillBill While Authorization or Purchase Payment

### ISSUE THREAD

**Issue by shekarnode** [Wovenware/killbill-braintree#3]
Hi team,

I m using this plugin to do PayPal transactions through killbill.

So i was able to install this plugin successfully and also able to add to an account  as payment method.

Now the problem is whenever we are doing transaction - i.e Authorize / Purchase (as per killbill terminology)

Note : the transaction is getting success at Braintree end.

I am getting below error related to DB connection / SQL issue -

![image](https://user-images.githubusercontent.com/3267543/119335125-8d3cd080-bca9-11eb-9f6e-f77dc9392f0b.png)

![image](https://user-images.githubusercontent.com/3267543/119335265-c8d79a80-bca9-11eb-9cd4-8ff3ccaa7157.png)

**Comment by wwldejesus** [comment]
Hi @shekarnode 

Were you able to complete the first step of installation regarding the configuration of the DB? Can you validate the db and that it contains the tables that are created once you execute ddl.sql?

Leslie

**Comment by shekarnode** [comment]
Hi Leslie,

Thanks for replying.

Yes I ran the ddl.sql script inside killbill schema.
it created 2 tables 
![image](https://user-images.githubusercontent.com/3267543/119368866-292e0280-bcd1-11eb-85c6-55088479ad47.png)

So when adding payment method , data is getting inserted in 'braintree_payment_methods' table.
![image](https://user-images.githubusercontent.com/3267543/119369160-7d38e700-bcd1-11eb-9872-8417ea563512.png)


But while doing authorization/purchase from killbill , the error occurs i.e. insertion in 'braintree_responses fails'.

![image](https://user-images.githubusercontent.com/3267543/119369359-b3766680-bcd1-11eb-901c-fa8e12b3d7c8.png)

**Comment by wwmrosario** [comment]
Hello @shekarnode, 

Can you try looking into the log file to see if there is additional information regarding the error? This log file is usually named killbill.out.

**Comment by shekarnode** [comment]
Hi @wwmrosario ,

extract the error from log .

```
4274 > POST http://killbill:8080/1.0/kb/accounts/440a64a6-1426-4f0c-8bc2-44cc72c7b678/payments?paymentMethodId=70ed6aaa-753f-45b3-b525-5087a4fea6a7
4274 > accept: application/json
4274 > user-agent: killbill/3.2.0; jruby 9.1.17.0 (2.3.3) 2018-04-20 d8b1ff9 OpenJDK 64-Bit Server VM 25.275-b01 on 1.8.0_275-8u275-b01-0ubuntu1~20.04-b01 +jit [linux-x86_64]
4274 > accept-encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
4274 > x-killbill-apikey: ordazzle-api-key
4274 > x-killbill-apisecret: ****************
4274 > cookie: JSESSIONID=5de9c3e5-3a7e-4bd2-9058-48601b604664
4274 > content-type: application/json
4274 > x-killbill-createdby: admin
4274 > x-killbill-reason: 600 - Alt payment method
4274 > x-killbill-comment: test new payment
4274 > x-request-id: ab3051e6-dd5f-4218-a3f1-aea0321a5685
4274 > host: killbill:8080
4274 > content-length: 61
4274 > 

2021-05-24T18:38:15,648+0000 lvl='INFO', log='DefaultPaymentApi', th='catalina-exec-198', xff='', rId='ab3051e6-dd5f-4218-a3f1-aea0321a5685', tok='ab3051e6-dd5f-4218-a3f1-aea0321a5685', aRId='1', tRId='1', ENTERING PaymentApi: transactionType='PURCHASE', accountId='440a64a6-1426-4f0c-8bc2-44cc72c7b678', paymentMethodId='70ed6aaa-753f-45b3-b525-5087a4fea6a7', amount='65', currency='USD'
2021-05-24T18:38:16,727+0000 lvl='INFO', log='Braintree', th='Plugin-th-43', xff='', rId='ab3051e6-dd5f-4218-a3f1-aea0321a5685', tok='ab3051e6-dd5f-4218-a3f1-aea0321a5685', aRId='1', tRId='1', [Braintree] [24/May/2021 18:38:16 +0000]] POST /merchants/grspkhpvy3mhcsc8/payment_methods/70ed6aaa-753f-45b3-b525-5087a4fea6a7/nonces
2021-05-24T18:38:20,093+0000 lvl='INFO', log='Braintree', th='Plugin-th-43', xff='', rId='ab3051e6-dd5f-4218-a3f1-aea0321a5685', tok='ab3051e6-dd5f-4218-a3f1-aea0321a5685', aRId='1', tRId='1', [Braintree] [24/May/2021 18:38:20 +0000]] POST /merchants/grspkhpvy3mhcsc8/transactions
2021-05-24T18:38:20,268+0000 lvl='INFO', log='DefaultPaymentApi', th='catalina-exec-198', xff='', rId='ab3051e6-dd5f-4218-a3f1-aea0321a5685', tok='ab3051e6-dd5f-4218-a3f1-aea0321a5685', aRId='1', tRId='1', EXITING PaymentApi: transactionType='PURCHASE', accountId='440a64a6-1426-4f0c-8bc2-44cc72c7b678', error='PAYMENT_INTERNAL_ERROR', exception='Internal payment error : org.jooq.exception.DataAccessException: SQL [insert into `braintree_responses` (`kb_account_id`, `kb_payment_id`, `kb_payment_transaction_id`, `transaction_type`, `amount`, `currency`, `braintree_id`, `additional_data`, `created_date`, `kb_tenant_id`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) returning `record_id`, `kb_account_id`, `kb_payment_id`, `kb_payment_transaction_id`, `transaction_type`, `amount`, `currency`, `braintree_id`, `additional_data`, `created_date`, `kb_tenant_id`]; (conn=74726) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'returning `record_id`, `kb_account_id`, `kb_payment_id`, `kb_payment_transaction' at line 1'
2021-05-24T18:38:20,278+0000 lvl='WARN', log='LoggingResponse', th='catalina-exec-198', xff='', rId='ab3051e6-dd5f-4218-a3f1-aea0321a5685', tok='ab3051e6-dd5f-4218-a3f1-aea0321a5685', aRId='1', tRId='1', Internal error
org.killbill.billing.payment.api.PaymentApiException: Internal payment error : org.jooq.exception.DataAccessException: SQL [insert into `braintree_responses` (`kb_account_id`, `kb_payment_id`, `kb_payment_transaction_id`, `transaction_type`, `amount`, `currency`, `braintree_id`, `additional_data`, `created_date`, `kb_tenant_id`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) returning `record_id`, `kb_account_id`, `kb_payment_id`, `kb_payment_transaction_id`, `transaction_type`, `amount`, `currency`, `braintree_id`, `additional_data`, `created_date`, `kb_tenant_id`]; (conn=74726) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'returning `record_id`, `kb_account_id`, `kb_payment_id`, `kb_payment_transaction' at line 1
	at org.killbill.billing.payment.core.sm.PaymentAutomatonRunner.runStateMachineOperation(PaymentAutomatonRunner.java:255)
	at org.killbill.billing.payment.core.sm.PaymentAutomatonRunner.run(PaymentAutomatonRunner.java:218)
	at org.killbill.billing.payment.core.PaymentProcessor.performOperation(PaymentProcessor.java:329)
	at org.killbill.billing.payment.core.PaymentProcessor.performOperation(PaymentProcessor.java:230)
	at org.killbill.billing.payment.core.PaymentProcessor.createPurchase(PaymentProcessor.java:118)
	at org.killbill.billing.payment.api.DefaultPaymentApi.createPurchase(DefaultPaymentApi.java:294)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor$1.execute(KillbillApiAopModule.java:76)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:35)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor.invoke(KillbillApiAopModule.java:92)
	at org.killbill.billing.util.security.AopAllianceMethodInvocationAdapter.proceed(AopAllianceMethodInvocationAdapter.java:45)
	at org.apache.shiro.authz.aop.AuthorizingAnnotationMethodInterceptor.invoke(AuthorizingAnnotationMethodInterceptor.java:68)
	at org.killbill.billing.util.security.AopAllianceMethodInterceptorAdapter.invoke(AopAllianceMethodInterceptorAdapter.java:32)
	at org.killbill.billing.payment.api.DefaultPaymentApi.createPurchaseWithPaymentControl(DefaultPaymentApi.java:325)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor$1.execute(KillbillApiAopModule.java:76)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:35)
	at org.killbill.billing.util.glue.KillbillApiAopModule$ProfilingMethodInterceptor.invoke(KillbillApiAopModule.java:92)
	at org.killbill.billing.util.security.AopAllianceMethodInvocationAdapter.proceed(AopAllianceMethodInvocationAdapter.java:45)
	at org.apache.shiro.authz.aop.AuthorizingAnnotationMethodInterceptor.invoke(AuthorizingAnnotationMethodInterceptor.java:68)
	at org.killbill.billing.util.security.AopAllianceMethodInterceptorAdapter.invoke(AopAllianceMethodInterceptorAdapter.java:32)
	at org.killbill.billing.jaxrs.resources.AccountResource.processPayment(AccountResource.java:1063)
	at org.killbill.billing.jaxrs.resources.AccountResource.processPayment(AccountResource.java:1011)
	at org.killbill.commons.skeleton.metrics.TimedResourceInterceptor.invoke(TimedResourceInterceptor.java:72)
	at org.killbill.billing.server.modules.JaxRSAopModule$JaxRsMethodInterceptor$1.execute(JaxRSAopModule.java:87)
	at org.killbill.billing.util.entity.dao.DBRouterUntyped.withRODBIAllowed(DBRouterUntyped.java:57)
	at org.killbill.billing.server.modules.JaxRSAopModule$JaxRsMethodInterceptor.invoke(JaxRSAopModule.java:82)
	at sun.reflect.GeneratedMethodAccessor621.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
	at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
	at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
	at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
	at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
	at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
	at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
	at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
	at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:558)
	at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:733)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)
	at com.google.inject.servlet.ServletDefinition.doServiceImpl(ServletDefinition.java:290)
	at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:280)
	at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:184)
	at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:89)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:85)
	at org.killbill.billing.server.security.TenantFilter.doFilter(TenantFilter.java:111)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at org.killbill.billing.server.filters.ResponseCorsFilter.doFilter(ResponseCorsFilter.java:75)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at ch.qos.logback.classic.helpers.MDCInsertingServletFilter.doFilter(MDCInsertingServletFilter.java:49)
	at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:82)
	at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:121)
	at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:133)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:44)
	at org.apache.shiro.web.servlet.AdviceFilter.executeChain(AdviceFilter.java:108)
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:137)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.shiro.guice.web.SimpleFilterChain.doFilter(SimpleFilterChain.java:41)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449)
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365)
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90)
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83)
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383)
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362)
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.codahale.metrics.servlet.AbstractInstrumentedFilter.doFilter(AbstractInstrumentedFilter.java:111)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:478)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:80)
	at org.apache.catalina.valves.rewrite.RewriteValve.invoke(RewriteValve.java:279)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:624)
	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:799)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1455)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.jooq.exception.DataAccessException: SQL [insert into `braintree_responses` (`kb_account_id`, `kb_payment_id`, `kb_payment_transaction_id`, `transaction_type`, `amount`, `currency`, `braintree_id`, `additional_data`, `created_date`, `kb_tenant_id`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) returning `record_id`, `kb_account_id`, `kb_payment_id`, `kb_payment_transaction_id`, `transaction_type`, `amount`, `currency`, `braintree_id`, `additional_data`, `created_date`, `kb_tenant_id`]; (conn=74726) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'returning `record_id`, `kb_account_id`, `kb_payment_id`, `kb_payment_transaction' at line 1
	at org.jooq_3.14.7.MARIADB.debug(Unknown Source)
	at org.jooq.impl.Tools.translate(Tools.java:2880)
	at org.jooq.impl.DefaultExecuteContext.sqlException(DefaultExecuteContext.java:757)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:389)
	at org.jooq.impl.InsertImpl.fetchOne(InsertImpl.java:1089)
	at org.killbill.billing.plugin.braintree.dao.BraintreeDao$3.withConnection(BraintreeDao.java:162)
	at org.killbill.billing.plugin.braintree.dao.BraintreeDao$3.withConnection(BraintreeDao.java:1)
	at org.killbill.billing.plugin.dao.PluginDao.execute(PluginDao.java:197)
	at org.killbill.billing.plugin.braintree.dao.BraintreeDao.addResponse(BraintreeDao.java:135)
	at org.killbill.billing.plugin.braintree.api.BraintreePaymentPluginApi.executeInitialTransaction(BraintreePaymentPluginApi.java:507)
	at org.killbill.billing.plugin.braintree.api.BraintreePaymentPluginApi.executeInitialTransaction(BraintreePaymentPluginApi.java:456)
	at org.killbill.billing.plugin.braintree.api.BraintreePaymentPluginApi.purchasePayment(BraintreePaymentPluginApi.java:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.killbill.billing.osgi.ContextClassLoaderHelper$ClassLoaderInvocationHandler$1.execute(ContextClassLoaderHelper.java:144)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:39)
	at org.killbill.billing.osgi.ContextClassLoaderHelper$ClassLoaderInvocationHandler.handleInvocation(ContextClassLoaderHelper.java:141)
	at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:86)
	at com.sun.proxy.$Proxy227.purchasePayment(Unknown Source)
	at org.killbill.billing.payment.core.sm.payments.PurchaseOperation.doCallSpecificOperationCallback(PurchaseOperation.java:47)
	at org.killbill.billing.payment.core.sm.payments.PaymentOperation.doOperation(PaymentOperation.java:153)
	at org.killbill.billing.payment.core.sm.payments.PaymentOperation.doSimpleOperationCallback(PaymentOperation.java:138)
	at org.killbill.billing.payment.core.sm.payments.PaymentOperation.access$000(PaymentOperation.java:53)
	at org.killbill.billing.payment.core.sm.payments.PaymentOperation$1.doOperation(PaymentOperation.java:130)
	at org.killbill.billing.payment.core.sm.payments.PaymentOperation$1.doOperation(PaymentOperation.java:127)
	at org.killbill.billing.payment.core.ProcessorBase$WithAccountLock.processAccountWithLock(ProcessorBase.java:179)
	at org.killbill.billing.payment.core.ProcessorBase$CallableWithAccountLock.call(ProcessorBase.java:162)
	at org.killbill.billing.payment.core.ProcessorBase$CallableWithAccountLock.call(ProcessorBase.java:143)
	at org.killbill.billing.payment.dispatcher.CallableWithRequestData.call(CallableWithRequestData.java:69)
	at org.killbill.commons.concurrent.WrappedCallable.call(WrappedCallable.java:45)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at org.killbill.commons.concurrent.WrappedRunnable.run(WrappedRunnable.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: (conn=74726) You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'returning `record_id`, `kb_account_id`, `kb_payment_id`, `kb_payment_transaction' at line 1
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.get(ExceptionMapper.java:177)
	at org.mariadb.jdbc.internal.util.exceptions.ExceptionMapper.getException(ExceptionMapper.java:110)
	at org.mariadb.jdbc.MariaDbStatement.executeExceptionEpilogue(MariaDbStatement.java:235)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:216)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.execute(MariaDbPreparedStatementClient.java:150)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeQuery(MariaDbPreparedStatementClient.java:164)
	at com.zaxxer.hikari.proxy.PreparedStatementProxy.executeQuery(PreparedStatementProxy.java:52)
	at com.zaxxer.hikari.proxy.HikariPreparedStatementProxy.executeQuery(HikariPreparedStatementProxy.java)
	at net.sf.log4jdbc.sql.jdbcapi.PreparedStatementSpy.executeQuery(PreparedStatementSpy.java:780)
	at org.jooq.tools.jdbc.DefaultPreparedStatement.executeQuery(DefaultPreparedStatement.java:99)
	at org.jooq.impl.AbstractDMLQuery.executeReturningQuery(AbstractDMLQuery.java:1230)
	at org.jooq.impl.AbstractDMLQuery.execute(AbstractDMLQuery.java:1039)
	at org.jooq.impl.AbstractQuery.execute(AbstractQuery.java:375)
	... 33 common frames omitted
Caused by: java.sql.SQLException: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'returning `record_id`, `kb_account_id`, `kb_payment_id`, `kb_payment_transaction' at line 1
Query is: insert into `braintree_responses` (`kb_account_id`, `kb_payment_id`, `kb_payment_transaction_id`, `transaction_type`, `amount`, `currency`, `braintree_id`, `additional_data`, `created_date`, `kb_tenant_id`) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) returning `record_id`, `kb_account_id`, `kb_payment_id`, `kb_payment_transaction_id`, `transaction_type`, `amount`, `currency`, `braintree_id`, `additional_data`, `created_date`, `kb_tenant_id`, parameters ['440a64a6-1426-4f0c-8bc2-44cc72c7b678','785efca3-0cdf-466c-bb7a-4e6da5d5b50e','88fcc024-c337-4f3d-9c5a-61598ba31c6b','PURCHASE',65,'USD','j70gsjve','{"bt_first_payment_reference_id":"j70gsjve","bt_payment_instrument_type":"paypal_account","bt_transaction_success":true,"bt_transaction_status":"SETTLING"}','2021-05-24 18:38:15.0','f9f7a3b3-4b70-47ed-b5d2-5009861f6071']
	at org.mariadb.jdbc.internal.util.LogQueryTool.exceptionWithQuery(LogQueryTool.java:153)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executeQuery(AbstractQueryProtocol.java:254)
	at org.mariadb.jdbc.MariaDbPreparedStatementClient.executeInternal(MariaDbPreparedStatementClient.java:209)
	... 42 common frames omitted
2021-05-24T18:38:20,279+0000 lvl='INFO', log='LoggingFilter', th='catalina-exec-198', xff='', rId='ab3051e6-dd5f-4218-a3f1-aea0321a5685', tok='ab3051e6-dd5f-4218-a3f1-aea0321a5685', aRId='1', tRId='1', 4274 * Server out-bound response
4274 < 500
4274 < Content-Type: application/json
4274 < 

2021-05-24T18:38:20,376+0000 lvl='INFO', log='BeatrixListener', th='bus_events-th', xff='', rId='', tok='ab3051e6-dd5f-4218-a3f1-aea0321a5685', aRId='1', tRId='1', Sending extBusEvent='DefaultBusExternalEvent{objectId=785efca3-0cdf-466c-bb7a-4e6da5d5b50e, accountId=440a64a6-1426-4f0c-8bc2-44cc72c7b678, tenantId=f9f7a3b3-4b70-47ed-b5d2-5009861f6071, objectType=PAYMENT, eventType=PAYMENT_FAILED}' from busEvent='DefaultPaymentInternalEvent{accountId=440a64a6-1426-4f0c-8bc2-44cc72c7b678, paymentId=785efca3-0cdf-466c-bb7a-4e6da5d5b50e, paymentTransactionId=88fcc024-c337-4f3d-9c5a-61598ba31c6b, amount=0, currency=USD, status=UNKNOWN, transactionType=PURCHASE, effectiveDate=2021-05-24T18:38:15.000Z, isApiPayment=true}'

```

**Comment by wwmrosario** [comment]
@shekarnode Thank you for the information provided, we will be looking into it.

**Comment by wwerodriguez** [comment]
Greetings @shekarnode,
Can you specify which version of MariaDB is being used?

**Comment by shekarnode** [comment]
@wwerodriguez 

I m using External MySQL DB Instance.

MySQL v5.7

**Comment by wwerodriguez** [comment]
Greetings @shekarnode.

It seems that the OSS version of JOOQ that you are using (3.14.7), only supports MySQL version 8.0.19. To support version MySQL 5.7, you would need to downgrade to JOOQ version 3.9. You can check the JOOQ Support Matrix at: https://www.jooq.org/download/support-matrix.

**Comment by wwerodriguez** [comment]
Thanks @shekarnode.
I am assuming this helped you with your issue. I am closing this issue due to lack of activity.
